### ISSUE TITLE
"sync to this" button gone on mobile

### ISSUE THREAD

**Issue by Xyloba** [henryperson/twitchmultivod#12]
as the title says the "sync to this" button on mobile is just randomly gone. 
ive been using "twitchmultivod.com" on mobile and it has been working pretty good for me, except now i cant sync anything up since the button is gone as of recently. (its still there on pc but i dont have easy access to one so i use mobile) i know that the button used to be there around 2-3 weeks ago, it would be appreciated is this could be fixed/reimplemented. Thank you.

**Comment by henryperson** [comment]
Sorry to get to this very late. Does it work to just tap the place where it could be? That's always been my experience on mobile, I have to tap where it would be for it to appear, then it works normally (disappearing after a few seconds).

If not I can look into it more.

**Comment by Xyloba** [comment]
Oh, yeah that works, kinda weird for it to be invisible but it works nonetheless so thank you for the tip.
