### ISSUE TITLE
Keep state after browser relaunch

### ISSUE THREAD

**Issue by fenhl** [henryperson/twitchmultivod#2]
If I quit and relaunch Firefox, other video players like YouTube and Twitch reopen at the exact same position where I left off. Twitch Multi Vod doesn't even remember which vods were open. It would be useful if it remembered that somehow.

**Comment by henryperson** [comment]
Pretty busy these days so not sure when I'll get a chance to add a fix for this, but it's a good suggestion. Probably the best way to do this would be to update the URL in the browser whenever a vod is added or removed. Then reopening the browser would trigger the URL parsing used in the share feature

**Comment by henryperson** [comment]
Got around to fixing this with the fix I described, so I'm going to close the issue. Feel free to re-open if you think it's still broken
