### ISSUE TITLE
Vods are cut out if there are too many

### ISSUE THREAD

**Issue by random42** [henryperson/twitchmultivod#3]
Example: [6 vods](https://twitchmultivod.com/#/956473698/956473611?t=0h56m60s/956451560/956450512/956479637/956481397)

I cannot see some of the top and bottom of the vods space. So I cannot use "Sync to this" button for example on the top ones. Also it seems that top and bottom bars also cover some of the vods. If I knew how to do fix this I'd do it, but I'm not versatile on frontend stuff sorry :(

Btw, great work, I really appreciate it.

**Comment by henryperson** [comment]
I can look into this a bit, but I'm pretty sure this is happening because Twitch requires its embedded VODs to be a minimum size. See the first line [here](https://dev.twitch.tv/docs/embed/video-and-clips). But I'll check it out and see if there's a way to bypass it

**Comment by random42** [comment]
Maybe you can just put them in a scroll view rather than fixed, idk..

**Comment by henryperson** [comment]
You're right. I put them in a scroll view and made the minimum size of VODs smaller. Forgot that I had manually set the minimum size in this app, so I set it to the smaller of their "400x300" requirement (400 width != 300 height with the aspect ratio I use, so the minimums there imply different sizes). Going to close this, feel free to re-open if you think it's still broken
