### ISSUE TITLE
Manual starting timecode per video

### ISSUE THREAD

**Issue by NPavie** [henryperson/twitchmultivod#4]
Hi,

First of all, thank you for this webapp !
(I was thinking of doing a similar app to watch simultaneous twitch and youtube VOD of streamers)

I stumble upon a sync issue between 2 VOD of different streamers, and i had some difficulties resyncing both videos using play/pause ^^'.
I was wondering if it could be possible to manually set a starting time code, by using a time input field instead of the video player progression bar for each loaded VOD ?

**Comment by henryperson** [comment]
Where in the UI are you thinking you'd want to set the timestamp? Per video or are you thinking a window that lets you set a timestamp for each video? I could see adding a window that says "enter a timestamp for each video that is at the same real time" and then we use that as the time offset. Though no promises on how quickly I could get to this feature as I've got another project that is taking up my free time these days.

In the mean time, I added the toggle on smart play for this reason—you can get the vods to be pretty close to other, turn smart play off, pause one until they're synced, and then turn smart play back on to watch

**Comment by NPavie** [comment]
I actually managed to do the sync as you said in the first place.
(the "issue" per say was starting/playing the videos to put them on a right timecode before launching both by toggling smart play).
I was thinking of a simple input per video (that would change the current video timecode), but the idea of a "start at" form/window with timecodes per video is also very interesting.

I'm not even sure others will find this functionnality useful (i happened to stumble upon unsynced vod streams, but i hope it is an exception in the twitch VOD ecosystem :) ) and as you said, it is already possible to do the sync by toggling of the smart play and syncing the timecodes using both the player progression bar and playing until the good timecode is obtained.
Its just that in that case, i had easily identified both timecodes and i lost myself a bit while trying to sync them with the twitch player in the first place ^^'

Its actually more of a missing feature of many majors video players like the twitch one.

**Comment by henryperson** [comment]
Going to close this for now since I don't think this would be a popular enough feature for it to be worth implementing. I'll re-open it if that changes. Thanks for taking the time to submit it though!
