### ISSUE TITLE
Allow query strings in vod URLs

### ISSUE THREAD

**Issue by fenhl** [henryperson/twitchmultivod#5]
If you copy a vod link from a channel's past broadcasts, you get a URL ending with `?filter=archives&sort=time`. For convenience, this should be recognized as a valid URL when pasted into the text field in the top toolbar.

**Comment by henryperson** [comment]
You mean it should just ignore everything after the vod id? That's pretty easy to fix just want to make sure I know what you're requesting.

**Comment by henryperson** [comment]
Also where are you copying the link from exactly? When I go to a channel's videos page (e.g. https://www.twitch.tv/xqcow/videos) and copy a link it just gives me the normal link, no parameters. Curious where you're finding the parameters

**Comment by fenhl** [comment]
At least the `filter` and `sort` parameters should be ignored. Maybe `t` could be used to set the sync point, but ignoring it would work too.

I'm getting these links from the “Past Broadcasts” page, e.g. <https://www.twitch.tv/xqcow/videos?filter=archives&sort=time>.

**Comment by henryperson** [comment]
Ok gotcha, yeah this is pretty easy to do. The `t` for the syncing point also should be pretty straightforward as that functionality is built into other parts of the site. I'll probably get to this in the next day or two.

**Comment by henryperson** [comment]
I fixed the query strings thing but haven't gotten around to timestamps. It's a bit more complicated than I had thought and I haven't had much time. I'll get to it at some point, but for now will close this issue.

Also for ease of adding videos, if you didn't see it check out the new feature I implemented where you can add videos by a streamer's username. Should be much easier than using links.
